package types

import "errors"

const (
	// UserMessage Indicates the message was generated by user
	UserMessage = MessageType(1)

	// BotMessage indicates the message was a reply from bot
	BotMessage = MessageType(2)
)

var (
	ErrAuthCode = errors.New("invalid auth code")
)

type MessageType int8

type Chat struct {
	AuthCode string `json:"auth_code"`

	// Messages in the conversation
	Messages []Message `json:"messages"`

	// Epoch timestamp of the last time a message is added to the conversation
	LastUpdated int64 `json:"last_updated"`
}

type Message struct {
	Content string      `json:"content"`
	MsgType MessageType `json:"msg_type"`
}
